description_general: description of the run  # General description, used for the OpenQuake job.ini file.
main_path: path/to/running/directory  #Path to the main running directory, assumed to have the needed structure.
oelf_source_model_filename: source_model.xml  # Name of the XML file with the source model to be used in OELF.
mapping_damage_states:
  no_damage: DS0
  dmg_1: DS1
  dmg_2: DS2
  dmg_3: DS3
  dmg_4: DS4
oelf:
  min_magnitude: 4.0  # Minimum magnitude to carry out a damage and loss assessment while running OELF.
  max_distance: 200.0  # Maximum epicentral distance between earthquake source and site to actually run the earthquake.
  continuous_ses_numbering: True  # If True, the software will assume there are as many stochastic event sets as indicated in 'ses_range', with an increment of 1.
  ses_range: 1, 10000  # Start and end number of the ID of the stochastic event sets, given as a list separated by comma and space (", ").
  rupture_region_properties:  # (Optional) Tectonic-region dependent configuration of regional rupture properties
    Volcanic Shallow:
      msr: WC1994  # Choice of magnitude scaling relation (must be supported by OpenQuake)
      area_mmax: 7.0  # Magnitude corresponding to the maximum rupture area permitted
      aspect_limits: 1.0, 1.5  # Limits to the uniform distribution used to sample aspect ratio
      default_usd: 0.0  # Default upper seismogenic depth (km) - will be over-ridden if specified in source
      default_lsd: 10.0  # Default lower seismogenic depth (km) - will be over-ridden if specified by source
    Active Shallow Crust:
      msr: Leonard2014_Interplate
      area_mmax: 7.5
      aspect_limits: 1.0, 1.5
      default_usd: 0.0
      default_lsd: 25.0
injuries_scale: 1, 2, 3, 4  # Scale of severity of injuries, given as a list separated by comma and space (", ").
injuries_longest_time: 1095  # Max. number of days since the time of an earthquake that will be used to calculate the number of occupants in the future.
time_of_day_occupancy:  # Factors by which the census population can be multiplied to obtain the people in the building at a certain time of the day.
  residential:
    day: 0.242853  # approx. 10 am to 6 pm
    night: 0.9517285  # approx. 10 pm to 6 am
    transit: 0.532079  # approx. 6 am to 10 am and 6 pm to 10 pm
  commercial:
    day: 0.4982155
    night: 0.0436495
    transit: 0.090751
  industrial:
    day: 0.4982155
    night: 0.0436495
    transit: 0.090751
timezone: "Europe/Rome"  # Local time zone in the format of the IANA Time Zone Database (https://www.iana.org/time-zones)
store_intermediate: True  # If True, intermediate results including intermediate exposure models and damage states will be stored. Intended for debugging.
store_openquake: True  # If True, OpenQuake HDF5 files will be stored and jobs will be kept in OpenQuake's database. Intended for debugging.
post_process:
  collect_csv: True  ## If True, individual damage and loss output CSVs will be collected under one RLA and one OELF CSV file.
