description_general: description of the run  # General description, used for the OpenQuake job.ini file
main_path: path/to/running/directory  #Path to the main running directory, assumed to have the needed structure.
mapping_damage_states:
  no_damage: DS0
  dmg_1: DS1
  dmg_2: DS2
  dmg_3: DS3
  dmg_4: DS4
